Devops. FirstSprint. 3 incements
eugeniylennik/alertics pull request #4
Opened 2023-03-09 12:39 UTC by eugeniylennik

2023-03-09 14:16 UTC, edylcrm commented on cmd/agent/main.go
> +func main() {
В этом спринте не нужно было реализовывать агент, по этому файл этот игнорирую на code review

2023-03-09 14:21 UTC, eugeniylennik commented on cmd/agent/main.go
> +func main() {
А в первом инкременте разве не нужно было реализовать агента?

2023-03-09 14:48 UTC, edylcrm requested changes

2023-03-09 14:48 UTC, edylcrm commented on cmd/server/main.go
> +	go func() {
Сервис не нужно запускать в отдельной горутине. Стоит запускать прям в main

2023-03-09 14:48 UTC, edylcrm commented on internal/handlers/handler.go
> +	m *storage.MemStorage
Здесь стоит завязаться на интерфейс, а не на конкретную реализацию

2023-03-09 14:48 UTC, edylcrm commented on internal/handlers/handler.go
> +	v, err := strconv.ParseFloat(value, 64)
Для counter используется int64, не будет ли тут ошибки?

2023-03-09 14:48 UTC, edylcrm commented on internal/storage/storage.go
> +	Gauge   map[string]float64
Не стоит делать Gauge и Counter публичными и брать значения прям из них. Для этого стоит сделать отдельные методы Gauge(name string) (float64, error), Counter(name string) (int64, error) т.к. в дальнейшем метрики будут храниться в БД или в каком-то другом месте и порядок их получения будет другой. Лучше сразу завязаться на интерфейс и везде использовать его.

2023-03-09 14:48 UTC, edylcrm commented on internal/storage/storage.go
> +func (ms *MemStorage) AddMetrics(m metrics.Data) error {
И я бы этот метод разбил на два. Отдельно Gauge и Counter, но это по желанию. В дальнейшей так будет проще масштабировать и изменять логику

2023-03-09 14:48 UTC, edylcrm commented on internal/client/client.go
> +		return errors.New("empty metrics")
Может просто не оправлять? Это же не обязательно ошибка если метрики пустые

2023-03-09 14:48 UTC, edylcrm commented on internal/handlers/handler.go
> +		value = float64(v)
В это случае value должно быть int64

2023-03-09 14:48 UTC, edylcrm commented on cmd/agent/main.go
> +func main() {
Не совсем понял как это должно работать. В задании сказано: 

_Задание для трека «Сервис сбора метрик и алертинга»
Разработайте агент по сбору рантайм-метрик и их последующей отправке на сервер по протоколу HTTP. Разработку нужно вести с использованием [шаблона](https://github.com/yandex-praktikum/go-musthave-devops-tpl.git).
Агент должен собирать метрики двух типов:
gauge, тип float64
counter, тип int64
В качестве источника метрик используйте пакет runtime.
Нужно собирать следующие метрики:
Имя метрики: "Alloc", тип: gauge
Имя метрики: "BuckHashSys", тип: gauge
..._
На сколько я понял нужно собирать данные из runtime/metrics. 
Что это такое: https://pkg.go.dev/runtime/metrics
Как примерно делать: https://spec-zone.ru/go/runtime/metrics/index

2023-03-09 14:53 UTC, eugeniylennik commented on cmd/agent/main.go
> +func main() {
Метрики собираются из пакета runtime/metrics 

https://github.com/eugeniylennik/alertics/pull/4/files#diff-6e56d7c057f6a96124b78f2b669dd7dface2718c304aece205017d114b3a7088R15

2023-03-09 14:54 UTC, edylcrm commented on cmd/agent/main.go
> +	<-ctx.Done()
И если так делать, то две горутины запущенный выше будут сразу же завершаться. А должны срабатывать каждые 2/10 секунд.

И хорошим топом является чтение сигнала ОС как тут https://stackoverflow.com/questions/56735056/golang-catch-sigterm-and-continue-application

2023-03-09 14:56 UTC, eugeniylennik commented on cmd/agent/main.go
> +	<-ctx.Done()
Они не завершаются, там в бесконечном цикле получаем данные по тикеру каждые 2 секунды для получения и каждые 10 секунд для отправки

2023-03-09 15:07 UTC, edylcrm commented on cmd/agent/main.go
> +func main() {
Увидел, сначала не заметил

2023-03-09 15:08 UTC, edylcrm commented on cmd/agent/main.go
> +	<-ctx.Done()
Да, еще раз посмотрел, context не завершается и в этом проблема. Лучше добавить обработчик сигналов OC и если получили какой-то сигнал, отправить метрики которые остались и корректно завершить процесс

2023-03-09 15:09 UTC, edylcrm commented on cmd/agent/main.go
> +	"github.com/eugeniylennik/alertics/internal/client"
Тут форматирование поправить, но если на это нет линтера/тестов то по желанию

2023-03-09 15:10 UTC, edylcrm commented on cmd/agent/main.go
> +			if len(m) > 0 {
В sendMetrics это проверяется, можно здесь не проверять

2023-03-09 15:14 UTC, edylcrm commented on internal/handlers/handler.go
> +type APIResponse struct {
Не используется, давай удалим

2023-03-09 15:16 UTC, edylcrm commented on internal/handlers/handler.go
> +	w.Write(b)
Отдает ошибку, может обработаем?

2023-03-09 15:17 UTC, edylcrm commented on internal/handlers/handler.go
> +	b, _ := json.Marshal(s.m)
Здесь так же лучше сделать отдельный метод для получения всех метрик, а не пытаться преобразовать структуру в json

2023-03-09 15:18 UTC, edylcrm commented on internal/handlers/handler_test.go
> +	"github.com/eugeniylennik/alertics/internal/router"
Тут тоже сортировка

2023-03-09 15:20 UTC, edylcrm commented on internal/metrics/metrics.go
> +	inc = 0
Вот тут единственный вопрос нужно ли скидывать счетчик при отправки метрик. Обычно counter должен скидываться при отправки на 0, но в задании на это ответа нет. :)
Если надо скидывать, то здесь проще создать структуру которая будет содержать этот inc

2023-03-09 15:24 UTC, edylcrm commented on internal/server/shutdown.go
> +func ShutdownServer(s *http.Server) {
Вот что-то похожее в agent надо сделать

2023-03-09 15:29 UTC, eugeniylennik commented on internal/metrics/metrics.go
> +	inc = 0
Тут немного в другом заключается идея, при отправке метрик с типом counter необходимо не замещать предыдущее полученное значение, а инкрементить его, в данном случае эта переменная используется для инкремента значения обновления метрики counter

2023-03-09 15:30 UTC, edylcrm commented on internal/metrics/metrics.go
> +	inc = 0
Я о том, что вообще counter всегда сбрасывается при отправки, в твоем случае сброса не происходит, но и в задании к спринту про это не сказано. Так что оставляй как есть

2023-03-09 15:36 UTC, edylcrm commented on internal/handlers/handler.go
> +	m *storage.MemStorage
<img width="690" alt="image" src="https://user-images.githubusercontent.com/20055276/224074191-2cdf4117-aae1-4041-949b-e51ab4ee700f.png">
В задании как раз сказано об этом

2023-03-09 18:19 UTC, eugeniylennik commented on cmd/server/main.go
> +	go func() {
В задании указано, что сервер должен штатно завершаться по сигналам, как я буду отлавливать сигналы, если сервер будут запускать не в отдельной горутине?

2023-03-09 18:26 UTC, eugeniylennik commented on internal/handlers/handler.go
> +	v, err := strconv.ParseFloat(value, 64)
Нет, мы ведь получаем значение из URLParams в виде строки, которую потом парсим в вещественное число

2023-03-10 07:56 UTC, edylcrm commented on internal/server/shutdown.go
> +	<-signalChan
Здесь можно читать какой сигнал пришел и писать его в лог

2023-03-10 08:24 UTC, edylcrm commented on internal/metrics/metrics.go
> +	inc = 0
Все таки давай скидывать счетчик в 0 при отправки метрик, так будет правильней

2023-03-10 08:29 UTC, edylcrm commented on internal/server/shutdown.go
> +	ctx, cancelShutdown := context.WithTimeout(context.Background(), 5*time.Second)
Кажется что 5 секунд слишком много для завершения

2023-03-10 08:30 UTC, edylcrm commented on internal/server/shutdown.go
> +	<-signalChan
Так же можно добавить signal.Stop(signalChan)

2023-03-10 08:30 UTC, edylcrm commented on internal/server/shutdown.go
> +	if err := s.Shutdown(ctx); err != nil {
Так же можно добавить s.SetKeepAlivesEnabled(false) чтобы сервис не создавать keepalives соединения т.к. собирается выключаться

2023-03-10 08:36 UTC, edylcrm commented on cmd/server/main.go
> +	go func() {
Тут просто не особо понятно как это должно работать. По какой-то причине сервер вернул ошибку и записал ее в лог. Но основная горутина все так же работает и ждет сигнал от ОС. Возможно тут стоит писать ошибку в канал и в main слушать канал, если пришла ошибка, то завершать программу.

2023-03-13 06:27 UTC, eugeniylennik commented on cmd/server/main.go
> +	go func() {
Исправлено

2023-03-13 06:27 UTC, eugeniylennik commented on internal/handlers/handler.go
> +	m *storage.MemStorage
Исправлено

2023-03-13 06:27 UTC, eugeniylennik commented on internal/storage/storage.go
> +	Gauge   map[string]float64
Исправлено

2023-03-13 06:27 UTC, eugeniylennik commented on internal/storage/storage.go
> +func (ms *MemStorage) AddMetrics(m metrics.Data) error {
Исправлено

2023-03-13 06:27 UTC, eugeniylennik commented on internal/client/client.go
> +		return errors.New("empty metrics")
Исправлено

2023-03-13 06:28 UTC, eugeniylennik commented on internal/handlers/handler.go
> +		value = float64(v)
Исправлено

2023-03-13 14:45 UTC, edylcrm requested changes

2023-03-13 14:45 UTC, edylcrm commented on cmd/server/main.go
> +	go func() {
Тут стоит поменять местами. Слушать сигналы ОС лучше в основной горутине, а сервис запускать через горутину

2023-03-13 14:45 UTC, edylcrm commented on cmd/agent/main.go
> +	<-ctx.Done()
Здесь обработку сигналов добавишь?

2023-03-13 14:45 UTC, edylcrm commented on internal/storage/storage.go
> +	gauge   map[string]float64
Так же стоит добавить sync.RWMutex чтобы не было гонок

2023-03-13 14:45 UTC, edylcrm commented on internal/storage/storage.go
> +type Repository interface {
В го принято объявлять интерфейсы в месте использования, подробней тут: https://www.youtube.com/watch?v=eYHCCht8eX4
Т.е. его надо унести в handler

2023-03-13 14:45 UTC, edylcrm commented on internal/server/shutdown.go
> +func ShutdownServer(s *http.Server) {
Сейчас этот метод нигде не используется. Он еще нужен?

2023-03-13 14:47 UTC, eugeniylennik commented on cmd/server/main.go
> +	go func() {
До этого так и было, предыдущий комментарий от Вас, что сервис нужно запускать в main)

2023-03-14 07:13 UTC, eugeniylennik commented on cmd/agent/main.go
> +	"github.com/eugeniylennik/alertics/internal/client"
Так форматирует утилита fmt

2023-03-14 07:25 UTC, eugeniylennik commented on cmd/agent/main.go
> +	<-ctx.Done()
Добавил

2023-03-14 07:25 UTC, eugeniylennik commented on cmd/agent/main.go
> +			if len(m) > 0 {
Исправлено

2023-03-14 07:47 UTC, eugeniylennik commented on cmd/server/main.go
> +	go func() {
Исправлено

2023-03-14 07:47 UTC, eugeniylennik commented on internal/handlers/handler.go
> +type APIResponse struct {
Удалено

2023-03-14 07:48 UTC, eugeniylennik commented on internal/handlers/handler.go
> +	w.Write(b)
Исправлено

2023-03-14 07:48 UTC, eugeniylennik commented on internal/handlers/handler.go
> +	b, _ := json.Marshal(s.m)
Исправлено

2023-03-14 07:48 UTC, eugeniylennik commented on internal/handlers/handler_test.go
> +	"github.com/eugeniylennik/alertics/internal/router"
Сортировка утилитой fmt

2023-03-14 07:48 UTC, eugeniylennik commented on internal/server/shutdown.go
> +func ShutdownServer(s *http.Server) {
Удалено

2023-03-14 08:00 UTC, eugeniylennik commented on internal/storage/storage.go
> +type Repository interface {
Исправлено

2023-03-14 16:39 UTC, edylcrm requested changes

2023-03-14 16:39 UTC, edylcrm commented on internal/storage/storage.go
> +	gauge   map[string]float64
Давай все таки добавить мьютекс

2023-03-15 14:22 UTC, eugeniylennik commented on internal/storage/storage.go
> +	gauge   map[string]float64
Добавил

2023-03-15 15:10 UTC, edylcrm approved these changes

2023-03-15 15:34 UTC, merged